Repository ls1intum/artemis-android, pull requests merged in 2025-03, with the labels that each got.

#428 `Bugifx`: Fix Post horizontal Padding
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/post/PostWithBottomSheet.kt
Labels: ready to merge

#447 `Feature`: Mention FAQ in chat
  core/common/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/common/markdown/ArtemisMarkdownTransformer.kt
  core/common/src/main/res/drawable/faq_link_icon.xml
  core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/compose/ImageVectorExtension.kt
  core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/deeplinks/ArtemisDeeplink.kt
  core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/deeplinks/FaqDeeplinks.kt
  core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/markdown/PostArtemisMarkdownTransformer.kt
  core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/material/DefaultTab.kt
  feature/exercise-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/exerciseview/home/ExerciseScreenBody.kt
  feature/faq-test/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/faq_test/FaqRepositoryMock.kt
  feature/faq/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/faq/repository/FaqRepository.kt
  feature/faq/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/faq/repository/FaqRepositoryImpl.kt
  feature/faq/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/faq/service/remote/FaqRemoteServiceImpl.kt
  feature/faq/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/faq/ui/detail/FaqDetailUi.kt
  feature/lecture-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/lectureview/LectureScreenBody.kt
  feature/metis/build.gradle.kts
  feature/metis/conversation/build.gradle.kts
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/conversation_module.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/ConversationChatListScreen.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/ConversationThreadScreen.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/ConversationViewModel.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/reply/MarkdownStyle.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/reply/MarkdownTextField.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/reply/ReplyTextField.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/reply/autocomplete/AutoCompleteType.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/reply/autocomplete/AutoCompletionUseCase.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/reply/autocomplete/ReplyAutoCompleteHintProvider.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/reply/autocomplete/ReplyAutoCompletePopup.kt
  feature/metis/conversation/src/main/res/values/markdown_textfield_strings.xml
  feature/metis/conversation/src/main/res/values/reply_textfield.xml
  feature/metis/conversation/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/reply/ReplyTextFieldUiTest.kt
  feature/metis/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/communication_moduleTest.kt
Labels: ready to merge

#456 `Chore`: Adapt to server api change
  core/common/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/common/markdown/ArtemisMarkdownTransformer.kt
  core/core-test/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/test/test_setup/course_creation/CourseManagementRequests.kt
  core/data/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/data/service/Api.kt
  core/data/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/data/service/network/impl/AccountDataServiceImpl.kt
  core/data/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/data/service/network/impl/CourseExerciseServiceImpl.kt
  core/data/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/data/service/network/impl/CourseServiceImpl.kt
  core/data/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/data/service/network/impl/ExerciseServiceImpl.kt
  core/data/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/data/service/network/impl/ParticipationServiceImpl.kt
  core/data/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/data/service/network/impl/ServerTimeServiceImpl.kt
  core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/markdown/PostArtemisMarkdownTransformer.kt
  feature/course-registration/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/courseregistration/service/impl/CourseRegistrationServiceImpl.kt
  feature/course-view/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/courseview/ExerciseListOverviewE2eTest.kt
  feature/dashboard/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/dashboard/service/impl/DashboardServiceImpl.kt
  feature/exercise-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/exerciseview/service/impl/TextEditorServiceImpl.kt
  feature/exercise-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/exerciseview/service/impl/TextSubmissionServiceImpl.kt
  feature/exercise-view/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/exercise_view/participate/text_exercise/BaseExerciseTest.kt
  feature/faq/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/faq/service/remote/FaqRemoteServiceImpl.kt
  feature/lecture-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/lectureview/service/impl/LectureServiceImpl.kt
  feature/lecture-view/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/lecture_view/LectureE2eTest.kt
  feature/login/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/login/service/network/impl/LoginServiceImpl.kt
  feature/login/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/login/service/network/impl/RegisterServiceImpl.kt
  feature/login/src/test/java/de/tum/informatics/www1/artemis/native_app/feature/login/RegisterEndToEndTest.kt
  feature/metis/code-of-conduct/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/codeofconduct/service/impl/CodeOfConductServiceImpl.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/service/network/impl/MetisModificationServiceImpl.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/service/network/impl/SavedPostServiceImpl.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/service/network/metis_resources.kt
  feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/service/network/impl/ChannelServiceImpl.kt
  feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/service/network/impl/ConversationServiceImpl.kt
  feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/service/network/impl/NotificationSettingsServiceImpl.kt
  feature/quiz/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/quiz/service/impl/QuizExerciseServiceImpl.kt
  feature/quiz/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/quiz/service/impl/QuizParticipationServiceImpl.kt
  feature/quiz/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/quiz/QuizParticipationBaseE2eTest.kt
  feature/quiz/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/quiz/QuizPracticeParticipationE2eTest.kt
  feature/quiz/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/quiz/QuizWaitingScreenE2eTest.kt
Labels: ready to merge

#432 `Feature`: Delete Channel
  feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/settings/overview/ConversationOtherSettings.kt
  feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/settings/overview/ConversationSettingsBody.kt
  feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/settings/overview/ConversationSettingsScreen.kt
  feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/settings/overview/ConversationSettingsViewModel.kt
  feature/metis/manage-conversations/src/main/res/values/conversation_settings_strings.xml
  feature/metis/manage-conversations/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/settings/ChannelSettingsE2eTest.kt
  feature/metis/manage-conversations/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/settings/ConversationSettingsBaseE2eTest.kt
  feature/metis/shared/src/debug/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/ConversationServiceStub.kt
  feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/content/dto/conversation/ChannelChat.kt
  feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/service/network/ConversationService.kt
  feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/service/network/impl/ConversationServiceImpl.kt
  feature/metis/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/ui/SinglePageConversationBody.kt
Labels: ready to merge, api calls

#434 `Feature`: Add link previews to chat
  feature/course-view/src/debug/kotlin/de/tum/informatics/www1/artemis/native_app/feature/courseview/MessagingScreenshots.kt
  feature/metis-test/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metistest/MetisServiceStub.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/service/model/LinkPreview.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/service/network/MetisService.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/service/network/impl/MetisServiceImpl.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/ConversationViewModel.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/chatlist/MetisChatList.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/post/LinkPreviewColumn.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/post/PostItem.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/post/PostWithBottomSheet.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/post/util/LinkPreviewUtil.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/thread/MetisThreadUi.kt
  feature/metis/conversation/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/BaseChatUITest.kt
  feature/metis/conversation/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/post/LinkPreviewTest.kt
Labels: ready to merge, api calls

#444 `Feature`: Add version code to push notification registrattion
  app/src/main/java/de/tum/informatics/www1/artemis/native_app/android/app_module.kt
  app/src/main/java/de/tum/informatics/www1/artemis/native_app/android/ui/MainActivity.kt
  app/src/main/java/de/tum/informatics/www1/artemis/native_app/android/ui/RootNavGraph.kt
  core/common/build.gradle.kts
  core/common/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/common/app_version/AppVersion.kt
  core/common/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/common/app_version/AppVersionProvider.kt
  core/common/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/common/app_version/NormalizedAppVersion.kt
  core/common/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/common/common_module.kt
  core/common/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/core/common/app_version/NormalizedAppVersionTest.kt
  core/core-test/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/test/core_test_modules.kt
  feature/force-update/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/force_update/repository/UpdateRepository.kt
  feature/force-update/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/force_update/repository/UpdateUtil.kt
  feature/force-update/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/force_update/service/UpdateService.kt
  feature/force-update/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/force_update/ui/UpdateNavGraph.kt
  feature/force-update/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/force_update/ui/UpdateScreen.kt
  feature/force-update/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/force_update/update_module.kt
  feature/force-update/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/force_update/UpdateUtilTest.kt
  feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/push_module.kt
  feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/service/impl/PushNotificationConfigurationServiceImpl.kt
  feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/service/impl/UploadPushNotificationDeviceConfigurationWorker.kt
  feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/service/network/NotificationSettingsService.kt
  feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/service/network/impl/NotificationSettingsServiceImpl.kt
  feature/push/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/PushNotificationSettingsE2eTest.kt
  feature/quiz/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/quiz/QuizPracticeParticipationE2eTest.kt
  feature/settings/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/settings/ui/SettingsNavGraph.kt
  feature/settings/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/settings/ui/SettingsScreen.kt
Labels: ready to merge

#465 `Bugfix`: Autocompletion type does not reset
  core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/compose/OnTrueLaunchedEffect.kt
  feature/dashboard/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/dashboard/ui/CoursesOverview.kt
  feature/dashboard/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/dashboard/ui/SurveyHint.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/chatlist/MetisPostListHandler.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/reply/ReplyTextField.kt
Labels: ready to merge

#466 `Bugfix`: Fix members scrolling bug
  feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/settings/members/ConversationMembersBody.kt
  feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/settings/members/ConversationMembersViewModel.kt
  feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/settings/members/MembersDataSource.kt
Labels: ready to merge

#448 `Feature`: Show forwarded messages
  app/src/main/java/de/tum/informatics/www1/artemis/native_app/android/db/AppDatabase.kt
  core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/Spacings.kt
  feature/course-view/src/debug/kotlin/de/tum/informatics/www1/artemis/native_app/feature/courseview/MessagingScreenshots.kt
  feature/exercise-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/exerciseview/ExerciseViewModel.kt
  feature/metis-test/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metistest/MetisServiceStub.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/service/network/MetisService.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/service/network/impl/MetisServiceImpl.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/service/storage/impl/MetisStorageServiceImpl.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/ConversationChatListScreen.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/ConversationViewModel.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/chatlist/ChatListItem.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/chatlist/ConversationChatListUseCase.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/chatlist/MetisChatList.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/chatlist/MetisSearchPagingSource.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/chatlist/RefreshablePagingSource.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/post/ForwardedMessageColumn.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/post/LinkPreviewColumn.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/post/PostItem.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/post/PostWithBottomSheet.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/saved_posts/SavedPostItem.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/shared/ForwardedMessagesHandler.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/thread/ConversationThreadUseCase.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/thread/MetisThreadUi.kt
  feature/metis/conversation/src/main/res/drawable/forward.xml
  feature/metis/conversation/src/main/res/values/post_strings.xml
  feature/metis/conversation/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/BaseChatUITest.kt
  feature/metis/conversation/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ConversationMessagesUITest.kt
  feature/metis/conversation/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/service/storage/impl/MetisStorageBaseTest.kt
  feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/content/dto/AnswerPost.kt
  feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/content/dto/BasePost.kt
  feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/content/dto/ForwardedMessage.kt
  feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/content/dto/IBasePost.kt
  feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/content/dto/IForwardedMessage.kt
  feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/content/dto/ISavedPost.kt
  feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/content/dto/IStandalonePost.kt
  feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/content/dto/PostingType.kt
  feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/content/dto/SavedPost.kt
  feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/content/dto/StandalonePost.kt
  feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/db/MetisDao.kt
  feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/db/entities/BasePostingEntity.kt
  feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/db/pojo/AnswerPostPojo.kt
  feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/db/pojo/PostPojo.kt
  feature/metis/shared/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/db/MetisDaoTest.kt
Labels: ready to merge, database changes, api calls

#452 `Improvement`: Only show relevant push notification settings
  core/model/build.gradle.kts
  core/model/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/model/account/Account.kt
  core/model/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/model/account/AccountAuthority.kt
  core/model/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/model/account/BaseAccount.kt
  core/model/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/model/account/User.kt
  core/model/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/core/model/account/AccountAuthorityTest.kt
  feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/content/dto/CourseUser.kt
  feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/content/dto/conversation/ConversationUser.kt
  feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/push_module.kt
  feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/ui/PushNotificationLocalization.kt
  feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/ui/PushNotificationSettingCategoriesListUi.kt
  feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/ui/PushNotificationSettingsUi.kt
  feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/ui/PushNotificationSettingsViewModel.kt
  feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/ui/model/PushNotificationSettingUtil.kt
  feature/push/src/main/res/values/push_notification_settings_strings.xml
  feature/push/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/PushNotificationSettingsE2eTest.kt
  feature/push/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/ui/model/PushNotificationSettingUtilTest.kt
Labels: ready to merge

#464 `Feature`: Add native emoji picker
  core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/common/BasicArtemisTextField.kt
  core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/compose/Keyboard.kt
  feature/course-view/build.gradle.kts
  feature/course-view/src/debug/kotlin/de/tum/informatics/www1/artemis/native_app/feature/courseview/MessagingScreenshots.kt
  feature/metis/conversation/build.gradle.kts
  feature/metis/conversation/emoji-picker/build.gradle.kts
  feature/metis/conversation/emoji-picker/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/emoji_picker/content/Emoji.kt
  feature/metis/conversation/emoji-picker/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/emoji_picker/content/EmojiCategory.kt
  feature/metis/conversation/emoji-picker/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/emoji_picker/emoji_picker_module.kt
  feature/metis/conversation/emoji-picker/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/emoji_picker/service/EmojiService.kt
  feature/metis/conversation/emoji-picker/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/emoji_picker/service/RecentEmojiService.kt
  feature/metis/conversation/emoji-picker/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/emoji_picker/service/impl/EmojiServiceImpl.kt
  feature/metis/conversation/emoji-picker/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/emoji_picker/service/impl/EmojiServiceStub.kt
  feature/metis/conversation/emoji-picker/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/emoji_picker/service/impl/RecentEmojiServiceImpl.kt
  feature/metis/conversation/emoji-picker/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/emoji_picker/ui/EmojiLineItem.kt
  feature/metis/conversation/emoji-picker/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/emoji_picker/ui/EmojiPicker.kt
  feature/metis/conversation/emoji-picker/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/emoji_picker/ui/EmojiPickerModalBottomSheet.kt
  feature/metis/conversation/emoji-picker/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/emoji_picker/ui/LocalEmojiProvider.kt
  feature/metis/conversation/emoji-picker/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/emoji_picker/ui/extensions/EmojiCategoryIdUiExtension.kt
  feature/metis/conversation/emoji-picker/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/emoji_picker/ui/extensions/LazyGridScopeExtension.kt
  feature/metis/conversation/emoji-picker/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/emoji_picker/ui/util/EmojiCategoryListUtil.kt
  feature/metis/conversation/emoji-picker/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/emoji_picker/ui/util/EmojiSearchUtil.kt
  feature/metis/conversation/emoji-picker/src/main/res/values/emoji_strings.xml
  feature/metis/conversation/emoji-picker/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/emoji_picker/ui/util/EmojiCategoryListUtilTest.kt
  feature/metis/conversation/emoji-picker/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/emoji_picker/ui/util/EmojiSearchUtilTest.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/TextFieldValueExtension.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/content/emoji/EmojiCategory.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/conversation_module.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/service/EmojiService.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/service/impl/EmojiServiceImpl.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/service/impl/EmojiServiceStub.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/LocalEmojiProvider.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/chatlist/MetisChatList.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/chatlist/MetisPostListHandler.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/post/PostItem.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/post/post_actions/PostContextBottomSheet.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/post/post_actions/PostReactionsBottomSheet.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/reply/MarkdownTextField.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/reply/ReplyTextField.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/thread/MetisThreadUi.kt
  feature/metis/conversation/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/BaseChatUITest.kt
  feature/metis/conversation/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/reply/ReplyTextFieldUiTest.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: ready to merge

#483 `Bugfix`: Fix padding issues
  feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/PotentiallyIllegalTextField.kt
  feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/create_channel/CreateChannelScreen.kt
  feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/settings/add_members/ConversationAddMembersScreen.kt
Labels: ready to merge

#484 `Improvement`: Add section count to conversation overview
  feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/overview/ConversationList.kt
  feature/metis/manage-conversations/src/main/res/values/conversation_overview_strings.xml
  feature/metis/manage-conversations/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/overview/ConversationOverviewE2eTest.kt
Labels: ready to merge

#481 `Improvement`: Update unread counter when clicking notification "Mark as read"
  app/src/main/AndroidManifest.xml
  feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/communication_notification_model/PushCommunicationDao.kt
  feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/communication_notification_model/PushCommunicationEntity.kt
  feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/notification_model/ArtemisNotification.kt
  feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/push_module.kt
  feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/service/CommunicationNotificationManager.kt
  feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/service/impl/PushNotificationHandlerImpl.kt
  feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/service/impl/notification_manager/BaseCommunicationNotificationReceiver.kt
  feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/service/impl/notification_manager/CommunicationNotificationManagerImpl.kt
  feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/service/impl/notification_manager/DeleteNotificationReceiver.kt
  feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/service/impl/notification_manager/MiscNotificationManager.kt
  feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/service/impl/notification_manager/ReplyReceiver.kt
  feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/service/impl/notification_manager/delete/DeleteNotificationReceiver.kt
  feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/service/impl/notification_manager/mark_as_read/MarkAsReadReceiver.kt
  feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/service/impl/notification_manager/mark_as_read/MarkConversationAsReadWorker.kt
  feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/service/impl/notification_manager/reply/ReplyReceiver.kt
  feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/service/impl/notification_manager/reply/UpdateReplyNotificationWorker.kt
  feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/service/impl/notification_manager/util/NotificationTargetManager.kt
  feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/service/impl/notification_manager/util/bitmap_util.kt
Labels: ready to merge

#500 `Chore`: Replace .sp usage with MaterialTheme.typography
  core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/common/DataStateUi.kt
  core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/common/InfoMessageCard.kt
  core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/common/course/CourseItem.kt
  feature/login/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/login/AccountUi.kt
  feature/login/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/login/login/LoginUi.kt
  feature/login/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/login/login/login_options/Saml2BasedLogin.kt
  feature/quiz/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/quiz/screens/WaitForQuizStartScreen.kt
Labels: ready to merge

#502 `Chore`: Adapt Announcement Title Styling
  core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/material/colors/PostColors.kt
  feature/metis/conversation/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/shared/ui/post/PostMainContent.kt
Labels: ready to merge

#490 `Feature`: Allow users to upload profile picture
  app/src/main/java/de/tum/informatics/www1/artemis/native_app/android/ui/MainActivity.kt
  core/data/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/data/service/Api.kt
  core/data/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/data/service/impl/ArtemisContextBasedServiceImpl.kt
  core/model/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/model/account/Account.kt
  core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/LocalArtemisContextProvider.kt
  core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/artemis_context_provider_extensions.kt
  core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/common/BottomSheetActionButton.kt
  core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/common/DataStateUi.kt
  core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/markdown/PostArtemisMarkdownTransformer.kt
  core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/markdown/link_resolving/MarkdownLinkResolverImpl.kt
  core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/remote_images/impl/ArtemisImageProviderImpl.kt
  core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/ui_module.kt
  core/ui/src/main/res/values/data_state_ui_strings.xml
  feature/exercise-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/exerciseview/ExerciseViewModel.kt
  feature/exercise-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/exerciseview/exercise_module.kt
  feature/exercise-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/exerciseview/home/ExerciseScreen.kt
  feature/exercise-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/exerciseview/participate/textexercise/TextExerciseParticipationScreen.kt
  feature/exercise-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/exerciseview/participate/textexercise/TextExerciseParticipationViewModel.kt
  feature/exercise-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/exerciseview/viewresult/ViewResultScreen.kt
  feature/exercise-view/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/exercise_view/participate/text_exercise/ExerciseOverviewE2eTest.kt
  feature/exercise-view/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/exercise_view/participate/text_exercise/TextExerciseParticipationE2eTest.kt
  feature/metis/code-of-conduct/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/codeofconduct/service/impl/CodeOfConductServiceImpl.kt
  feature/metis/conversation/saved-posts/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/saved_posts/ui/SavedPostWithActions.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/service/network/impl/MetisModificationServiceImpl.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/post/post_actions/PostContextBottomSheet.kt
  feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/ui/MetisViewModel.kt
  feature/metis/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/ui/SinglePageConversationBodyViewModel.kt
  feature/settings/build.gradle.kts
  feature/settings/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/settings/service/ChangeProfilePictureService.kt
  feature/settings/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/settings/service/ChangeProfilePictureServiceImpl.kt
  feature/settings/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/settings/settings_module.kt
  feature/settings/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/settings/ui/CommonSettingElements.kt
  feature/settings/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/settings/ui/SettingsNavGraph.kt
  feature/settings/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/settings/ui/SettingsScreen.kt
  feature/settings/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/settings/ui/SettingsViewModel.kt
  feature/settings/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/settings/ui/account/AccountSettingsScreen.kt
  feature/settings/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/settings/ui/account/ChangeProfilePictureBottomSheet.kt
  feature/settings/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/settings/ui/account/ImagePickerAndCropper.kt
  feature/settings/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/settings/ui/account/krop/ImagePicker.kt
  feature/settings/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/settings/ui/util/ProfilePictureBitmapUtil.kt
  feature/settings/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/settings/ui/util/ProfilePictureUploadResult.kt
  feature/settings/src/main/res/values/account_settings_strings.xml
  gradle/libs.versions.toml
Labels: ready to merge

#509 `Chore`: Switch to artemis.tum.de instance
  app/src/tum/AndroidManifest.xml
  app/src/unrestricted/AndroidManifest.xml
  build-logic/convention/src/main/kotlin/commonConfiguration/KotlinAndroid.kt
  core/datastore/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/datastore/defaults/ArtemisInstances.kt
  core/datastore/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/datastore/impl/ServerConfigurationServiceImpl.kt
  core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/deeplinks/ArtemisDeeplink.kt
  readme.md
Labels: ready to merge

#511 `Feature`: Filter messages in chats
  feature/course-view/src/debug/kotlin/de/tum/informatics/www1/artemis/native_app/feature/courseview/MessagingScreenshots.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/service/network/MetisService.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/service/network/impl/MetisServiceImpl.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/ConversationChatListScreen.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/ConversationViewModel.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/chatlist/ConversationChatListUseCase.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/chatlist/MetisRemoteMediator.kt
  feature/metis/conversation/src/main/res/values/conversation_strings.xml
  feature/metis/conversation/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ConversationMessagesE2eTest.kt
  feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/content/MetisFilter.kt
Labels: ready to merge

#515 `Bugfix`: Fix lecture unit pdfs loading error
  app/src/main/java/de/tum/informatics/www1/artemis/native_app/android/ui/RootNavGraph.kt
  core/data/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/data/service/Api.kt
  core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/remote_images/impl/ArtemisImageProviderImpl.kt
  feature/exercise-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/exerciseview/ExerciseViewUi.kt
  feature/exercise-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/exerciseview/home/ExerciseScreen.kt
  feature/exercise-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/exerciseview/home/ExerciseScreenBody.kt
  feature/exercise-view/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/exercise_view/participate/text_exercise/ExerciseOverviewE2eTest.kt
  feature/lecture-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/lectureview/LectureScreenUi.kt
Labels: ready to merge

#505 `Bugfix`: Back Navigation Work Around
  app/src/main/java/de/tum/informatics/www1/artemis/native_app/android/ui/RootNavGraph.kt
  core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/compose/NavigationBackButton.kt
  feature/course-registration/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/courseregistration/RegisterForCourseUi.kt
  feature/course-registration/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/courseregistration/CourseRegistrationE2eTest.kt
  feature/exercise-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/exerciseview/ExerciseViewUi.kt
  feature/exercise-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/exerciseview/home/ExerciseScreen.kt
  feature/exercise-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/exerciseview/home/ExerciseScreenTopAppBar.kt
  feature/faq/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/faq/ui/detail/FaqDetailUi.kt
  feature/lecture-view/src/debug/kotlin/de/tum/informatics/www1/artemis/native_app/feature/lectureview/LectureViewSnapshots.kt
  feature/lecture-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/lectureview/LectureScreenUi.kt
  feature/quiz/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/quiz/participation/QuizParticipationScreen.kt
  feature/quiz/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/quiz/view_result/ViewQuizResultScreen.kt
  feature/settings/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/settings/ui/SettingsNavGraph.kt
  feature/settings/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/settings/ui/SettingsScreen.kt
  feature/settings/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/settings/ui/account/AccountSettingsScreen.kt
Labels: ready to merge
