Repository ls1intum/artemis-android, pull requests merged in 2025-04, with the labels that each got.

#520 `Improvment`: Add Subgrouping to Lecture and Exercise List
  feature/course-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/courseview/TimeFrame.kt
  feature/course-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/courseview/TimeFrameUtils.kt
  feature/course-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/courseview/ui/CourseViewModel.kt
  feature/course-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/courseview/ui/LectureListUi.kt
  feature/course-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/courseview/ui/TimeFrameItemsLazyColumn.kt
  feature/course-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/courseview/ui/exercise_list/ExerciseListUi.kt
  feature/course-view/src/main/res/values/course_ui_strings.xml
Labels: ready to merge

#538 `Chore`: Use new file upload URL for FAQs
  feature/faq/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/faq/ui/FaqArtemisMarkdownTransformer.kt
Labels: ready to merge

#539 `Feature`: Toggle Channel Privacy
  feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/settings/overview/ConversationOtherSettings.kt
  feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/settings/overview/ConversationSettingsBody.kt
  feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/settings/overview/ConversationSettingsViewModel.kt
  feature/metis/manage-conversations/src/main/res/values/conversation_settings_strings.xml
  feature/metis/manage-conversations/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/settings/ChannelSettingsE2eTest.kt
  feature/metis/manage-conversations/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/settings/ConversationSettingsBaseE2eTest.kt
  feature/metis/shared/src/debug/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/ConversationServiceStub.kt
  feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/service/network/ConversationService.kt
  feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/service/network/impl/ConversationServiceImpl.kt
Labels: ready to merge

#537 `Feature`: Feature Toggle Base Mechanism
  app/src/main/java/de/tum/informatics/www1/artemis/native_app/android/ui/MainActivity.kt
  core/model/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/model/server_config/ProfileInfo.kt
  feature/force-update/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/force_update/FeatureAvailability.kt
  feature/force-update/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/force_update/repository/UpdateRepository.kt
  feature/force-update/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/force_update/repository/UpdateUtil.kt
  feature/force-update/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/force_update/service/UpdateService.kt
  feature/force-update/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/force_update/update_module.kt
  feature/force-update/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/force_update/UpdateUtilTest.kt
Labels: ready to merge

#530 `Chore`: Adapt requests for saved post and forwarded messages endpoints
  feature/metis/conversation/saved-posts/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/saved_posts/service/SavedPostServiceImpl.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/service/network/impl/MetisServiceImpl.kt
  feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/content/dto/SavedPostPostingType.kt
  feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/content/dto/SavedPostStatus.kt
Labels: ready to merge, api calls

#534 `Chore`: Adjust messages filter and get-messages Request
  feature/course-view/src/debug/kotlin/de/tum/informatics/www1/artemis/native_app/feature/courseview/MessagingScreenshots.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/service/network/impl/MetisServiceImpl.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/ConversationChatListScreen.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/chatlist/ConversationChatListUseCase.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/chatlist/MetisRemoteMediator.kt
  feature/metis/conversation/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ConversationMessagesE2eTest.kt
  feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/service/network/impl/ChannelServiceImpl.kt
  feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/content/MetisFilter.kt
Labels: ready to merge, api calls

#541 `Chore`: Combine `ConversationAddMembersScreen` and `CreatePersonalConversationScreen`
  feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/common/ConversationUserSelectionScreen.kt
  feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/common/PotentiallyIllegalTextField.kt
  feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/create_channel/CreateChannelScreen.kt
  feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/create_personal_conversation/CreatePersonalConversationScreen.kt
  feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/settings/add_members/ConversationAddMembersScreen.kt
  feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/settings/overview/ConversationInfoSettings.kt
  feature/metis/manage-conversations/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/members/ConversationAddMemberSettingsE2eTest.kt
  feature/metis/manage-conversations/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/overview/CreateConversationE2eTest.kt
Labels: ready to merge

#540 `Chore`: Add abstract ReloadableViewModel
  core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/ReloadableViewModel.kt
  core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/exercise/BaseExerciseListViewModel.kt
  feature/course-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/courseview/ui/CourseViewModel.kt
  feature/course-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/courseview/ui/course_overview/CourseUiScreen.kt
  feature/dashboard/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/dashboard/ui/CourseOverviewViewModel.kt
  feature/dashboard/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/dashboard/ui/CoursesOverview.kt
  feature/exercise-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/exerciseview/ExerciseViewModel.kt
  feature/exercise-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/exerciseview/ExerciseViewUi.kt
  feature/exercise-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/exerciseview/home/ExerciseScreen.kt
  feature/exercise-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/exerciseview/participate/textexercise/TextExerciseParticipationScreen.kt
  feature/exercise-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/exerciseview/participate/textexercise/TextExerciseParticipationViewModel.kt
  feature/faq/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/faq/ui/detail/FaqDetailUi.kt
  feature/faq/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/faq/ui/detail/FaqDetailViewModel.kt
  feature/faq/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/faq/ui/overview/FaqOverviewUi.kt
  feature/faq/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/faq/ui/overview/FaqOverviewViewModel.kt
  feature/lecture-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/lectureview/LectureScreenBody.kt
  feature/lecture-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/lectureview/LectureViewModel.kt
  feature/login/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/login/AccountUi.kt
  feature/login/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/login/BaseAccountViewModel.kt
  feature/login/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/login/saml2_login/Saml2LoginScreen.kt
  feature/login/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/login/saml2_login/Saml2LoginViewModel.kt
  feature/metis/conversation/saved-posts/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/saved_posts/ui/SavedPostsScreen.kt
  feature/metis/conversation/saved-posts/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/saved_posts/ui/SavedPostsViewModel.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/ConversationChatListScreen.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/ConversationThreadScreen.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/ConversationViewModel.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/thread/MetisThreadUi.kt
  feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/browse_channels/BrowseChannelsScreen.kt
  feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/browse_channels/BrowseChannelsViewModel.kt
  feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/overview/ConversationOverviewBody.kt
  feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/overview/ConversationOverviewViewModel.kt
  feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/settings/SettingsBaseViewModel.kt
  feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/settings/members/ConversationMembersBody.kt
  feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/settings/members/ConversationMembersViewModel.kt
  feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/settings/overview/ConversationSettingsBody.kt
  feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/settings/overview/ConversationSettingsScreen.kt
  feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/settings/overview/ConversationSettingsViewModel.kt
  feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/ui/MetisViewModel.kt
  feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/ui/member_selection/MemberSelection.kt
  feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/ui/member_selection/MemberSelectionBaseViewModel.kt
  feature/metis/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/ui/user_conversation/NavigateToUserConversationUi.kt
  feature/metis/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/ui/user_conversation/NavigateTouserConversationViewModel.kt
  feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/ui/PushNotificationSettingsUi.kt
  feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/ui/PushNotificationSettingsViewModel.kt
  feature/quiz/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/quiz/BaseQuizViewModel.kt
  feature/quiz/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/quiz/participation/QuizParticipationUi.kt
  feature/quiz/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/quiz/participation/QuizParticipationViewModel.kt
  feature/quiz/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/quiz/view_result/ViewQuizResultScreen.kt
  feature/settings/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/settings/ui/SettingsViewModel.kt
  feature/settings/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/settings/ui/account/AccountSettingsScreen.kt
Labels: ready to merge

#542 `Feature`: Show user profile pictures in mention search
  core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/Spacings.kt
  core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/compose/ArtemisPopupSurface.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/reply/autocomplete/AutoCompleteHint.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/reply/autocomplete/AutoCompletionUseCase.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/reply/autocomplete/ReplyAutoCompletePopup.kt
  feature/metis/conversation/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/BaseChatUITest.kt
  feature/metis/conversation/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ConversationAutoCompletionE2eTest.kt
  feature/metis/shared/src/debug/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/ConversationServiceStub.kt
  feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/service/network/ConversationService.kt
  feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/service/network/impl/ConversationServiceImpl.kt
  feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/ui/ConversationExtensions.kt
  feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/ui/member_selection/MemberSearchWithDropdownPopup.kt
Labels: ready to merge

#547 `Improvement`: Align Saved Post Design
  core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/material/colors/ComponentColors.kt
  feature/metis/conversation/saved-posts/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/saved_posts/ui/SavedPostWithActions.kt
  feature/metis/conversation/saved-posts/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/saved_posts/ui/SavedPostsScreen.kt
  feature/metis/conversation/saved-posts/src/main/res/values/saved_posts_strings.xml
  feature/metis/conversation/saved-posts/src/test/java/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/saved_posts/SavedPostsScreenUiTest.kt
  feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/overview/ConversationList.kt
  feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/overview/ConversationOverviewBody.kt
  feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/overview/ConversationOverviewViewModel.kt
  feature/metis/manage-conversations/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/overview/ConversationListUiTest.kt
  feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/ui/SavedPostStatusExtension.kt
  feature/metis/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/ConversationConfiguration.kt
  feature/metis/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/ui/SinglePageConversationBody.kt
Labels: ready to merge

#545 `Chore`: Update playstore images
  app/build.gradle.kts
  app/src/main/java/de/tum/informatics/www1/artemis/native_app/android/ui/RootNavGraph.kt
  core/ui-test/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/test/ui_test_module.kt
  core/ui/build.gradle.kts
  core/ui/src/debug/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/PlayStoreScreenshots.kt
  core/ui/src/debug/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/ScreenshotColors.kt
  core/ui/src/debug/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/ScreenshotData.kt
  core/ui/src/debug/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/ScreenshotFrame.kt
  core/ui/src/debug/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/ScreenshotTheme.kt
  core/ui/src/debug/res/drawable/astronaut_square.jpg
  core/ui/src/debug/res/drawable/mars.png
  core/ui/src/debug/res/drawable/saturn5.png
  core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/common/course/CourseItem.kt
  core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/remote_images/impl/ArtemisImageProviderStub.kt
  feature/course-view/build.gradle.kts
  feature/course-view/src/debug/kotlin/de/tum/informatics/www1/artemis/native_app/feature/courseview/CourseViewScreenshots.kt
  feature/course-view/src/debug/kotlin/de/tum/informatics/www1/artemis/native_app/feature/courseview/ExerciseListScreenshots.kt
  feature/course-view/src/debug/kotlin/de/tum/informatics/www1/artemis/native_app/feature/courseview/MessagingScreenshots.kt
  feature/course-view/src/debug/kotlin/de/tum/informatics/www1/artemis/native_app/feature/courseview/ScreenshotCommunicationData.kt
  feature/course-view/src/debug/kotlin/de/tum/informatics/www1/artemis/native_app/feature/courseview/ScreenshotDefaults.kt
  feature/course-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/courseview/ui/course_overview/CourseUiScreen.kt
  feature/dashboard/build.gradle.kts
  feature/dashboard/src/debug/kotlin/de/tum/informatics/www1/artemis/native_app/feature/dashboard/DashboardScreenshots.kt
  feature/dashboard/src/debug/kotlin/de/tum/informatics/www1/artemis/native_app/feature/dashboard/SurveyHintServiceFake.kt
  feature/dashboard/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/dashboard/ui/CoursesOverview.kt
  feature/lecture-view/src/debug/kotlin/de/tum/informatics/www1/artemis/native_app/feature/lectureview/LectureViewScreenshot.kt
  feature/lecture-view/src/debug/kotlin/de/tum/informatics/www1/artemis/native_app/feature/lectureview/LectureViewSnapshots.kt
  feature/lecture-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/lectureview/LectureScreenBody.kt
  feature/lecture-view/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/lectureview/LectureScreenUi.kt
  feature/lecture-view/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/lecture_view/LectureE2eTest.kt
  feature/metis/conversation/emoji-picker/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/emoji_picker/ui/LocalEmojiProvider.kt
  feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/ConversationChatListScreen.kt
  feature/metis/conversation/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/BaseChatUITest.kt
  feature/metis/conversation/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/ConversationProfilePictureUiTest.kt
  feature/metis/shared/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/shared/ui/profile_picture/ProfilePicture.kt
  feature/quiz/src/debug/kotlin/de/tum/informatics/www1/artemis/native_app/feature/quiz/QuizScreenshots.kt
  gradle/libs.versions.toml
  playStoreScreenshots/smartphone/conversation.png
  playStoreScreenshots/smartphone/conversationOverview.png
  playStoreScreenshots/smartphone/dashboard.png
  playStoreScreenshots/smartphone/exerciseList.png
  playStoreScreenshots/smartphone/lecture.png
  playStoreScreenshots/smartphone/quiz.png
  readme.md
Labels: ready for review

#546 `Improvement`: Conversation Information Adjustments
  core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/common/ArtemisSection.kt
  feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/create_channel/CreateChannelScreen.kt
  feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/settings/ConversationMemberListItem.kt
  feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/settings/members/ConversationMembersBody.kt
  feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/settings/members/ConversationMembersScreen.kt
  feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/settings/overview/ConversationInfoSettings.kt
  feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/settings/overview/ConversationMemberSettings.kt
  feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/settings/overview/ConversationOtherSettings.kt
  feature/metis/manage-conversations/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/ui/conversation/settings/overview/ConversationSettingsBody.kt
  feature/metis/manage-conversations/src/main/res/values/conversation_members_strings.xml
  feature/metis/manage-conversations/src/main/res/values/conversation_settings_strings.xml
  feature/metis/manage-conversations/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/members/ConversationMemberSettingsE2eTest.kt
  feature/metis/manage-conversations/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/manageconversations/settings/ChannelSettingsE2eTest.kt
  feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/ui/PushNotificationSettingCategoriesListUi.kt
  feature/settings/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/settings/ui/CommonSettingElements.kt
  feature/settings/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/settings/ui/SettingsScreen.kt
  feature/settings/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/settings/ui/account/AccountSettingsScreen.kt
Labels: ready to merge
